export interface ImportedListingData {
  source: 'ss.ge' | 'myhome.ge';
  sourceUrl: string;
  sourceId: string;
  title: string;
  description: string;
  type: string;
  dealType: string;
  buildingStatus: string;
  condition: string;
  price: string;
  pricePerSqm: string;
  currency: string;
  area: string;
  rooms: string;
  bedrooms: string;
  bathrooms: string;
  floor: string;
  totalFloors: string;
  city: string;
  district: string;
  address: string;
  street: string;
  streetNumber: string;
  cadastralCode: string;
  lat: number;
  lng: number;
  images: string[];
  youtubeUrl: string;
  matterportUrl: string;
  agentName: string;
  agentPhone: string;
  agentEmail: string;
  projectType: string;
  wetPoint: string;
  balconyCount: string;
  balconyArea: string;
  verandaArea: string;
  loggiaArea: string;
  waitingArea: string;
  yearBuilt: string;
  ceilingHeight: string;
  livingRoomArea: string;
  storageArea: string;
  parking: string[];
  heating: string[];
  hotWater: string[];
  buildingMaterials: string[];
  windowsMaterials: string[];
  furniture: string[];
  propertyAmenities: string[];
  buildingFeatures: string[];
  badges: string[];
  isPremium: boolean;
  isFeatured: boolean;
  isNew: boolean;
  meta: {
    viewCount?: number;
    vipLabel?: string;
    importedFields?: number;
    /** True when the source had no coordinates and the pin fell back to Tbilisi centre. */
    coordsFallback?: boolean;
    /** 'partial' means something important is missing and needs typing in by hand. */
    quality?: 'ok' | 'partial';
    missingFields?: string[];
    warnings?: string[];
  };
}
